### ISSUE TITLE
pod 2.1.3 for iOS 8.3

### ISSUE THREAD

**Issue by emonster** [enormego/EGOCache#49]
Is there a pod 'EGOCache', '>= 2.1.3' for iOS 8.3
Nullability specifier '__nonnull' cannot be applied to non-pointer type 'NSString'; did you mean to apply the specifier to the pointer?

**Comment by shnhrrsn** [comment]
2.1.3 was pushed to cocoapods [a little while ago](https://github.com/CocoaPods/Specs/blob/master/Specs/EGOCache/2.1.3/EGOCache.podspec.json).. Are you getting the error with 2.1.3 or 2.1.2?

**Comment by emonster** [comment]
Thank you!
Getting the error with 2.1.2

**Comment by bimawa** [comment]
Thx for fast update!

**Comment by emonster** [comment]
Hi, when I use pod 'EGOCache', '>= 2.1.3'  to get the update... I get...
"Unable to satisfy the following requirements: - `EGOCache (>= 2.1.3)` required by `Podfile`"
Is this the correct call? If I just use pod 'EGOCache' I get the old version 2.1.2

**Comment by emonster** [comment]
ok, this way works, i get 2.1.3
    pod 'EGOCache', :git => 'https://github.com/enormego/EGOCache.git'

**Comment by shnhrrsn** [comment]
Yeah, if you explicitly specify it works fine -- I experience this myself for a while after a new release, eventually it starts working.

It's possible I'm doing something wrong with publishing, but AFAIK, all you're supposed to do after is `pod trunk push`.

**Comment by emonster** [comment]
cool man, thank you!
