### ISSUE TITLE
compile error.

### ISSUE THREAD

**Issue by huji0624** [enormego/EGOCache#60]
EGOCache.m:328:61: error: no visible @interface for 'NSImageRep' declares the selector 'representationUsingType:properties:'
        [self setData:[[[anImage representations] objectAtIndex:0] representationUsingType:NSPNGFileType properties:nil] forKey:key withTimeoutInterval:timeoutInterval];
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.



Xcode Version 8.3.3 (8E3004b)
OSX 10.12.5

**Comment by shnhrrsn** [comment]
Apologies for the delay -- this should be fixed in v2.2.0
