### ISSUE TITLE
warning: Month 13 is out of bounds  //In Xcode9, iOS11

### ISSUE THREAD

**Issue by BeiXiao** [enormego/EGOCache#61]
because NSDate in _cacheInfo write to plist file
`
[_cacheInfo writeToFile:cachePathForKey(_directory, @"EGOCache.plist") atomically:YES];
`
hope fix it
Thanks

**Comment by xusion** [comment]
今天早上我也遇到这个问题，找了几个小时才定位到是这个库的问题。

**Comment by buttcmd** [comment]
It seems bug in SDK not from EGOCache.

Everything looks like it's working fine although i can see the log too.

**Comment by xusion** [comment]
注释这句[_cacheInfo writeToFile:cachePathForKey(_directory, @"EGOCache.plist") atomically:YES];就不会出现这个提示Month 13 is out of bounds。
然后作者早点修复一下。

**Comment by xusion** [comment]
我发现问题是在plist保存nsdate时发生的。我把保存的nsdate转为nsstring，就不会出现这个提示。但我不清楚这样做会不会出现性能上的差异。

**Comment by shnhrrsn** [comment]
Closing this out as it's an OS bug: https://encrypted.google.com/search?hl=en&q=%22Month%2013%20is%20out%20of%20bounds%22
